apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expensetracker
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: expensetracker.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expensetracker
                port:
                  number: {{ .Values.service.port }}