apiVersion: v1
kind: Service
metadata:
  name: expensetracker
  labels:
    app: expensetracker
spec:
  selector:
    app: expensetracker
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}