# kubeless-function.yaml
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: expensetracker-function
  namespace: default
spec:
  runtime: java1.8
  handler: com.cloudnativeplayground.expensetracker.Handler::handleRequest
  deps: |
    <dependencies>
  function-content-type: text/plain
  function: |-
    public class Handler {
      public String handleRequest(String input) {
          return "Hello, " + input + " from Expense Tracker!";
      }
    }
